name: Build web-IDE

on:
  push:
    branches:
      - main

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: 6.6.2
          arch: win64_msvc2019_64
          modules: qtwebengine

      - name: Configure CMake
        run: cmake -B build -S . -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build --config Release

      - name: List build output
        run: dir build\Release

      - name: Find executable
        id: findexe
        shell: pwsh
        run: |
          $exe = Get-ChildItem build/Release/*.exe | Select-Object -First 1
          echo "exe=$($exe.FullName)" >> $env:GITHUB_OUTPUT

      - name: Deploy Qt
        run: |
          windeployqt build/Release/web-ide.exe

            # ADD THIS
      - name: Install Inno Setup
        run: choco install innosetup -y

      # ADD THIS
      - name: Build Installer
        run: |
          iscc packaging/windows/installer.iss

      - name: Upload Build
        uses: actions/upload-artifact@v4
        with:
          name: webide-windows
          path: |
            build/Release
            packaging/windows/dist